### ISSUE TITLE
Should there be a settings page?

### ISSUE THREAD

**Issue by wafflestomper** [mattzollinhofer/teachy#44]
For instance to change the color options for the columns...

Or to highlight or not highlight numbers that are higher than the total possible?

**Comment by mattzollinhofer** [comment]
I tend to lean pretty heavily against providing options if possible - I'd
much rather pick good defaults for things like colors especially. We can
definitely discuss though.

On Tue, Jan 3, 2017 at 12:24 PM Brian Zollinhofer <notifications@github.com>
wrote:

For instance to change the color options for the columns...


Or to highlight or not highlight numbers that are higher than the total
possible?




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mattzollinhofer/teachy/issues/44>, or mute the thread

**Comment by wafflestomper** [comment]
Yeah, I know you do... :)

**Comment by mattzollinhofer** [comment]
Have any other good default color suggestions? I hate what's there right
now...

**Comment by mattzollinhofer** [comment]
Options == complications that people rarely use...

**Comment by wafflestomper** [comment]
Your opinion != true

**Comment by mattzollinhofer** [comment]
We can reopen this once people start using it and there are things that really feel necessary. I don't want to do this until some really obvious options emerge.

**Comment by wafflestomper** [comment]
Makes sense!


--------------------------------
Brian Zollinhofer
St. Christopher's School
Middle School Instructional Technologist
--------------------------------
