### ISSUE TITLE
Teacher Grade Book view - Red background for late assignments

### ISSUE THREAD

**Issue by wafflestomper** [mattzollinhofer/teachy#67]
Some way to tell if an assignment was late in the teacher view.  Light shade of red background in cell? A small red triangle in the corner of the cell?

Not essential, but I wonder if there is a way to double click the cell to toggle "late flag" on and off? A kid who is absent and would be flagged by the system as late could be unflagged by teacher?

**Comment by mattzollinhofer** [comment]
You gotta learn how to separate ideas :-). I did the first thing (background color) -- I didn't do the red triangle because it's harder and we're trying to keep the input box super tight already. I could do that though if you'd rather it.

The late flag bit doesn't make a lot of sense until I restructure the assignment/notes/ixl/etc like we've talked about.
